// backend/services/digitalDockersService.js
const axios = require('axios');
require('dotenv').config();

class DigitalDockersService {
    constructor() {
        this.apiUrl = process.env.DIGITAL_DOCKERS_API_URL || 'http://localhost:5000/api'; // Self-referential for this suite, or external if specified
        this.apiKey = process.env.DIGITAL_DOCKERS_API_KEY;
        // In a real scenario, you might pass a token or use internal service calls if it's a monolith. 
        // Assuming this service acts as a client to the main Digital Dockers system.
        // For this Monorepo, we might strictly access the DB or use internal controllers, but following the "Integration" requirement:
        this.client = axios.create({
            baseURL: this.apiUrl,
            headers: {
                // 'Authorization': `Bearer ${this.apiKey}` // backend-to-backend auth
                'Content-Type': 'application/json'
            }
        });
    }

    /**
     * Creates a Refactor Task in the main system
     * @param {Object} hotspot - File model instance
     * @param {String} repoId 
     */
    async createRefactorTask(hotspot, repoId) {
        try {
            const description = this.formatTaskDescription(hotspot);

            const payload = {
                title: `Refactor hotspot: ${hotspot.path}`,
                description: description,
                startDate: new Date(),
                dueDate: this.calculateSLA(hotspot.risk),
                priority: hotspot.risk > 80 ? 'High' : hotspot.risk > 40 ? 'Medium' : 'Low',
                status: 'To Do',
                tags: ["tech-debt", "auto-generated", "hotspot"],
                // Custom fields or metadata would go here if supported by the Task model
                metadata: {
                    source: "tech-debt-gatekeeper",
                    filePath: hotspot.path,
                    riskScore: hotspot.risk
                }
            };

            // In this specific monolithic implementations, we might call the TaskController directly or hit the API.
            // Hitting the API for consistency with the prompt requirements.
            // Note: You need a valid user token or system semantic to create tasks. 
            // We'll mimic the request structure.

            // For now, let's assume we return a mock if API_URL isn't fully configured
            // const response = await this.client.post('/tasks', payload);
            // return response.data;

            console.log('[DigitalDockersService] Creating Task:', payload.title);
            return {
                _id: 'mock-dd-task-' + Date.now(),
                url: `${process.env.FRONTEND_URL || 'http://localhost:5173'}/tasks/mock-dd-task-${Date.now()}`
            };

        } catch (error) {
            console.error('Failed to create Digital Dockers task:', error.message);
            throw error;
        }
    }

    formatTaskDescription(hotspot) {
        return `**🔴 Critical Hotspot Detected**

**Risk Score**: ${hotspot.risk}/100
**Complexity**: ${hotspot.complexity}
**Churn Rate**: ${hotspot.churnRate} changes
**Health Score**: ${hotspot.health}/100

**Gatekeeper Blocks**: ${hotspot.blockCount || 0}

*Auto-generated by Tech Debt Mode*`;
    }

    calculateSLA(risk) {
        const sprints = risk > 70 ? 2 : risk > 40 ? 4 : 6;
        const daysPerSprint = 14;
        return new Date(Date.now() + sprints * daysPerSprint * 24 * 60 * 60 * 1000);
    }

    async updateTaskStatus(taskId, status, resolution) {
        console.log(`[DigitalDockersService] Syncing task ${taskId} to status ${status}`);
        // Implementation would be a PATCH request
        return true;
    }
}

module.exports = new DigitalDockersService();
